### ISSUE TITLE
error in iOS 9

### ISSUE THREAD

**Issue by apptaro** [anonyco/Force-DOM-reflow-JS#1]
TypeError: undefined is not an object (evaluating 'Object.getOwnPropertyDescriptor(HTMLElement.prototype,"offsetHeight").get')

**Comment by apptaro** [comment]
The cause seems like iOS 9 bug: https://github.com/facebook/react/issues/9959

**Comment by anonyco** [comment]
Apptaro,

My apologies for taking so long to respond. I updated the library accordingly, and now it should be ready to go on all iOS devices (including iOS 9). If my solution does not work or you have other problems with the library, then you are always welcome to open another issue anytime. Thank you so much for bringing this bug to my attention.

Sincerely,
Jack G.

**Comment by apptaro** [comment]
@anonyco Thank you!
